# -*- coding: utf-8 -*-
#---------------------------------------------------------------------------#
# PALM-4U static driver configuration for  (10 m resolution)
#---------------------------------------------------------------------------#
# Attributes section
#---------------------------------------------------------------------------#
attributes:
  author: David Voellner
  contact_person: David Voellner (david.voellner@stud-mail.uni-wuerzburg.de)
  acronym: 
  comment: 
  data_content: Static driver for PALM4U Munich City domain, 10 m resolution
  location: Munich, Germany
  site: 
  institution: Earth Observation Research Center (EORC), University of Wuerzburg
  palm_version: 
  references: 
  source: 
  origin_time: "2025-02-16 00:00:00 +00"

#---------------------------------------------------------------------------#
# Settings section
#---------------------------------------------------------------------------#
settings:
  epsg: 25832
  season: summer

#---------------------------------------------------------------------------#
# Output section
#---------------------------------------------------------------------------#
output:
  path: /MUC_static_driver
  file_out: MUC_static_driver
  version: 1

#---------------------------------------------------------------------------#
# Input section
#---------------------------------------------------------------------------#
input_root:
  # input directory
  path: inst/extdata/processed_rasters
  
  # terrain
  # file_zt: not found

  # buildings LOD1
  file_buildings_2d: MUC_building_height_10.tif
  file_building_id: MUC_building_id_10.tif
  file_building_type: MUC_building_type_10.tif
 
  # bridges
  # file_bridges_2d: not found
  # file_bridges_id: not found
  
  # vegetation
  file_vegetation_type: MUC_lc_vegetation_type_10.tif
  # file_vegetation_height: not found

  # resolved vegetation (trees)
  # file_tree_height: not found
  # file_tree_crown_diameter: not found
  # file_tree_trunk_diameter: not found
  # file_tree_type: not found
  # file_lai: not found
  
  # water
  file_water_type: MUC_lc_water_type_10.tif

  # pavement
  file_pavement_type: MUC_lc_pavement_type_10.tif
  
  # file_soil_type: not found


#---------------------------------------------------------------------------#
# Domain definition (root domain)
# NOTE: the here defined domain needs to be completely within the boundaries of the data. Palm-4U cannot handle non-rectangular domains
#---------------------------------------------------------------------------#
domain_root:
  pixel_size: 10
  origin_x: 686750
  origin_y: 5335300
  nx: 39
  ny: 39
  dz: 10
  bridge_depth: 3
  buildings_3d: true
  street_trees: true
  overhanging_trees: true
  generate_vegetation_patches: true

